const menu = [
  {
    id: 1,
    title: 'Panqueca',
    category: 'café',
    price: 15.99,
    img: './images/item-1.jpeg',
    desc: `teste`,
  },
  {
    id: 2,
    title: 'Do dia',
    category: 'almoço',
    price: 13.99,
    img: './images/item-2.jpeg',
    desc: `teste`,
  },
  {
    id: 3,
    title: 'Sorvetão',
    category: 'sorvetes',
    price: 6.99,
    img: './images/item-3.jpeg',
    desc: `teste`,
  },
  {
    id: 4,
    title: 'Pãozinhos',
    category: 'café',
    price: 20.99,
    img: './images/item-4.jpeg',
    desc: `teste`,
  },
  {
    id: 5,
    title: 'ovo',
    category: 'almoço',
    price: 22.99,
    img: './images/item-5.jpeg',
    desc: `teste`,
  },
  {
    id: 6,
    title: 'oreo',
    category: 'sorvetes',
    price: 18.99,
    img: './images/item-6.jpeg',
    desc: `teste`,
  },
  {
    id: 7,
    title: 'bacon',
    category: 'café',
    price: 8.99,
    img: './images/item-7.jpeg',
    desc: `teste`,
  },
  {
    id: 8,
    title: 'brasil almoço',
    category: 'almoço',
    price: 12.99,
    img: './images/item-8.jpeg',
    desc: `teste`,
  },
  {
    id: 9,
    title: 'quero mais',
    category: 'sorvetes',
    price: 16.99,
    img: './images/item-9.jpeg',
    desc: `teste`,
  },
];
export default menu;
